import type { Metadata } from "next"
import localFont from "next/font/local"
import { ClerkProvider } from "@clerk/nextjs"
import { koKR } from "@clerk/localizations"

import { Toaster } from "@/components/ui/sonner"

import "./globals.css"

const pretendardFont = localFont({
  src: [
    {
      path: "../fonts/pretendard/PretendardVariable.woff2",
      weight: "45 920",
    }
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={koKR}>
      <html lang="en">
        <body className={pretendardFont.className}>
          {children}
          <Toaster
            position="top-center"
          />
        </body>
      </html>
    </ClerkProvider>
  )
}
